### Create a job
POST http://localhost:9090/api/jobs
Content-Type: application/json

{
  "salary": "236000",
  "title": "Software Developer 4",
  "description": "Testing the Description of a position"
}


### Get all Jobs
GET http://localhost:9090/api/jobs?page=1&pageSize=2


### Get the created job by ID
GET http://localhost:9090/api/jobs/e4f6ce48-41f9-449b-995a-3cfb6720de42

### Delete the Job
DELETE http://localhost:9090/api/jobs/{jobId}

###
# Authentication
POST http://localhost:9090/api/users/signup
Content-Type: application/json

{
  "username": "ivan",
  "password": "123456",
  "email": "ivan@testing.com"
}

###
POST http://localhost:9090/api/users/login
Content-Type: application/json

{
  "username": "ivan@testing.com",
  "password": "123456"
}

###
GET http://localhost:9090/api/users/logout
###
GET http://localhost:9090/api/validate